import { FC, useState } from 'react';
import { AxiosResponse, AxiosError } from 'axios';
import { Pet, PetStatusEnum, PetApiFactory } from '../../api/api';
import { AppDispatch } from '../../app/store';
import { addPet } from './petSlice';
import { useDispatch } from 'react-redux';

/**
 * Show a form to add a pet record.
 * Post a pet record in REST server to add db.json,
 * then dispatch PetSlice ation to add a pet record in store of the slice.
 * This form allows duplicated pet name to simplify the code.
 * @returns
 */
export const PetInput: FC = () => {
  /** Component level state of pet name. */
  const [petName, setPetName] = useState('');

  /** Component level state of errors. */
  const [message, setMessage] = useState('');

  /** Root dispach to access slice action. */
  const dispatch = useDispatch<AppDispatch>();

  /** Call Axios, then dispatch PetSlice action. */
  const postPet = (): void => {
    if (petName === '') {
      setMessage('Input a new pet name.');
      return;
    }
    setMessage('');
    const pet: Pet = {
      id: undefined,
      name: petName,
      category: undefined,
      photoUrls: [],
      status: PetStatusEnum.Available,
      tags: [],
    };
    /** Axios API which was generated by OpenAPI Generator. */
    const petApi = PetApiFactory(
      undefined,
      process.env.REACT_APP_REST_BASE,
      undefined
    );
    petApi
      .addPet(pet)
      .then((value: AxiosResponse<Pet>) => {
        console.log(value.status);
        /** Set pet Id whcih has been assigned by REST server. */
        pet.id = value.data.id;
        dispatch(addPet(pet));
      })
      .catch((reason: AxiosError) => {
        setMessage('API error : ' + reason.message);
      })
      .finally(() => {
        console.log('Completed.');
      });
  };

  return (
    <div>
      <p>Pet Input Component</p>
      <div>
        <p>
          <span>pet name : </span>
          <input
            value={petName}
            required
            onChange={(e) => setPetName(e.target.value)}
          />
        </p>
        <p>
          <button type="button" onClick={() => postPet()}>
            Add
          </button>
          {message}
        </p>
      </div>
    </div>
  );
};
